`ifndef DAISY_BITMAP_VH
`define DAISY_BITMAP_VH

// Exact conversion of the supplied 40x40 drawing; no resizing.
// Includes the original fur, detail, outline, white, and nose colors.
// Existing palette definitions take priority over these defaults.
// Transparent marker is skipped by render and is never displayed.

`ifndef RGB_DAISY_BODY
`define RGB_DAISY_BODY 24'h966F5D
`endif

`ifndef RGB_DAISY_DETAIL
`define RGB_DAISY_DETAIL 24'h664C41
`endif

`ifndef RGB_DAISY_LINES
`define RGB_DAISY_LINES 24'h000000
`endif

`ifndef RGB_DAISY_WHITE
`define RGB_DAISY_WHITE 24'hFFFFFF
`endif

`ifndef RGB_DAISY_NOSE
`define RGB_DAISY_NOSE 24'hFFA3B1
`endif

`ifndef RGB_DAISY_TRANSPARENT
`define RGB_DAISY_TRANSPARENT 24'hFF00FF
`endif

`define DAISY_WIDTH 40
`define DAISY_HEIGHT 40

`define DAISY_ROW_00 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_01 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_02 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_03 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_04 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_05 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_06 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_07 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_08 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_09 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_10 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_11 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_12 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_13 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_NOSE, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_14 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_15 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_16 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_17 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_18 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_19 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_20 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_21 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_22 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_23 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_24 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_25 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_26 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_27 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_28 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_29 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_30 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_WHITE, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_31 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_32 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_WHITE, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_33 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_34 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_35 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_DETAIL, `RGB_DAISY_DETAIL, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_36 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_DETAIL, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_DETAIL, `RGB_DAISY_DETAIL, `RGB_DAISY_DETAIL, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_37 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_BODY, `RGB_DAISY_LINES, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, \
    `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_BODY, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_38 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, \
    `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_LINES, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

`define DAISY_ROW_39 { \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, \
    `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT, `RGB_DAISY_TRANSPARENT \
}

// Row-major order: top-left pixel first, 24 bits per pixel.
`define DAISY_BITMAP { \
    `DAISY_ROW_00, \
    `DAISY_ROW_01, \
    `DAISY_ROW_02, \
    `DAISY_ROW_03, \
    `DAISY_ROW_04, \
    `DAISY_ROW_05, \
    `DAISY_ROW_06, \
    `DAISY_ROW_07, \
    `DAISY_ROW_08, \
    `DAISY_ROW_09, \
    `DAISY_ROW_10, \
    `DAISY_ROW_11, \
    `DAISY_ROW_12, \
    `DAISY_ROW_13, \
    `DAISY_ROW_14, \
    `DAISY_ROW_15, \
    `DAISY_ROW_16, \
    `DAISY_ROW_17, \
    `DAISY_ROW_18, \
    `DAISY_ROW_19, \
    `DAISY_ROW_20, \
    `DAISY_ROW_21, \
    `DAISY_ROW_22, \
    `DAISY_ROW_23, \
    `DAISY_ROW_24, \
    `DAISY_ROW_25, \
    `DAISY_ROW_26, \
    `DAISY_ROW_27, \
    `DAISY_ROW_28, \
    `DAISY_ROW_29, \
    `DAISY_ROW_30, \
    `DAISY_ROW_31, \
    `DAISY_ROW_32, \
    `DAISY_ROW_33, \
    `DAISY_ROW_34, \
    `DAISY_ROW_35, \
    `DAISY_ROW_36, \
    `DAISY_ROW_37, \
    `DAISY_ROW_38, \
    `DAISY_ROW_39 \
}

`endif
